### ISSUE TITLE
Not compatible with Zsh

### ISSUE THREAD

**Issue by Nerian** [imathis/octopress#117]
Hello,

The Rake task for creating a new post seems to be not compatible with Zsh.

```
rake new_post["Zombie Ninjas Attack: A survivor's retrospective"]   
zsh: no matches found: new_post[Zombie Ninjas Attack: A survivor's retrospective]
```

**Comment by strivingboy** [comment]
thanks good work for me

**Comment by liuyix** [comment]
I have the same problem, but using `the alias rake="noglob rake" ` works fine. Putting this suggestion in the doc may be helpful for many folks :-)
