### ISSUE TITLE
rake generate is time zone sensitive

### ISSUE THREAD

**Issue by johana-star** [imathis/octopress#1319]
I travelled from PST to EST.

When I ran rake generate it changed some html in all of my blog posts. When I switched my computer's local time to PST it reversed these changes.

I think this is an error because the html of old posts shouldn't change if you generate the site somewhere else.

I expect `rake generate` to not change html in older blog posts when the time zone shifts on your local machine.

**Comment by Manishearth** [comment]
I hacked this up by monkeypatching SafeYAML to strip out timezones.

https://github.com/Manishearth/manishearth.github.io/blob/source/plugins/manish_custom_slug.rb

This way, a post written in a certain timezone will get a slug correspondign to the date from that timezone. 

cc @domenic
