### ISSUE TITLE
changing or removing date in page causes generate failure

### ISSUE THREAD

**Issue by clayh53** [imathis/octopress#1416]
I am in the middle of building a site, and I followed the [recommendation](http://octopress.org/docs/blogging/) to eliminate the display of dates on my pages my deleting the date field completely in the yaml front matter at the top of each page. This was a mistake. Once I did this, I started getting the following error when using 'rake generate':

```
/Users/wcharmon/Sites/fresh_1/plugins/date.rb:15:in `ordinalize': undefined method `strftime' for nil:NilClass (NoMethodError)
    from /Users/wcharmon/Sites/fresh_1/plugins/date.rb:37:in `format_date'
    from /Users/wcharmon/Sites/fresh_1/plugins/date.rb:94:in `initialize'
    from /Users/wcharmon/.rvm/gems/ruby-1.9.3-p362/gems/jekyll-0.12.0/lib/jekyll/site.rb:143:in `new'
    from /Users/wcharmon/.rvm/gems/ruby-1.9.3-p362/gems/jekyll-0.12.0/lib/jekyll/site.rb:143:in `block in read_directories'
    from /Users/wcharmon/.rvm/gems/ruby-1.9.3-p362/gems/jekyll-0.12.0/lib/jekyll/site.rb:133:in `each'
    from /Users/wcharmon/.rvm/gems/ruby-1.9.3-p362/gems/jekyll-0.12.0/lib/jekyll/site.rb:133:in `read_directories'
    from /Users/wcharmon/.rvm/gems/ruby-1.9.3-p362/gems/jekyll-0.12.0/lib/jekyll/site.rb:101:in `read'
    from /Users/wcharmon/.rvm/gems/ruby-1.9.3-p362/gems/jekyll-0.12.0/lib/jekyll/site.rb:39:in `process'
    from /Users/wcharmon/.rvm/gems/ruby-1.9.3-p362/gems/jekyll-0.12.0/bin/jekyll:264:in `<top (required)>'
    from /Users/wcharmon/.rvm/gems/ruby-1.9.3-p362/bin/jekyll:19:in `load'
    from /Users/wcharmon/.rvm/gems/ruby-1.9.3-p362/bin/jekyll:19:in `<main>'
    from /Users/wcharmon/.rvm/gems/ruby-1.9.3-p362/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/wcharmon/.rvm/gems/ruby-1.9.3-p362/bin/ruby_noexec_wrapper:14:in `<main>'
```

And the site would fail to rebuild. 

Apparently, there is something going on when the date function in date.rb receives a value of nil instead of an actual date.  I was able to just comment out lines 14 and 15 in date.rb and got the site to succesfully rebuild:

```
# Returns an ordidinal date eg July 22 2007 -> July 22nd 2007
    def ordinalize(date)
      # date = datetime(date)
      # "#{date.strftime('%b')} #{ordinal(date.strftime('%e').to_i)}, #{date.strftime('%Y')}"
    end
```

I am a total ruby-noob, so I really don't have the chops to hack on the date.rb, but in researching this issue, it appears that the date.rb plugin had a [commit](https://github.com/imathis/octopress/pull/1336/files) three months back that actually had a test for by using  a format_date[] unless format_date[].nil sort of logic, but this is not in the main repository at the moment. And I couldn't help but notice the reference in the date.rb file at lines 63 and 92 to the "Monkey patch" which leads me to believe that issue is something that has been wrestled with before..

Anyway, it is something that needs to be looked at, and I wanted to post this crude hack here so anyone else running into the same issue can at least get their site to build.

**Comment by ZachSaucier** [comment]
Thanks for this! Otherwise I wouldn't have had the idea to look for empty date fields
