### ISSUE TITLE
SOLVED: Not generated stylesheets. Does not work preview

### ISSUE THREAD

**Issue by 3u128** [imathis/octopress#1424]
![idonthavestylesheets](https://f.cloud.github.com/assets/5946233/1599578/4d473ec2-535a-11e3-9113-fd69a40ac9de.png)
In the folder does not have a folder stylesheets and css. It's norm?
ls -a public/
.   assets    blog         images      javascripts  sitemap.xml
..  atom.xml  favicon.png  index.html  robots.txt

Does not work preview.
rake preview
Starting to watch source with Jekyll and Compass. Starting Rack on port 4000
rake aborted!
No such file or directory - compass watch
/home/bit2qubit/Documents/bit2qubit.github.io/Rakefile:81:in `spawn'
/home/bit2qubit/Documents/bit2qubit.github.io/Rakefile:81:in`block in <top (required)>'
Tasks: TOP => preview
(See full trace by running task with --trace)
bit2qubit@bit2qubit-1001P:~/Documents/bit2qubit.github.io$ Configuration from /home/bit2qubit/Documents/bit2qubit.github.io/_config.yml
Auto-regenerating enabled: source -> public
[2013-11-22 11:20:51] regeneration: 92 files changed
^C

Preview with --trace:

rake preview --trace*\* Invoke preview (first_time)
*\* Execute preview
Starting to watch source with Jekyll and Compass. Starting Rack on port 4000
rake aborted!
No such file or directory - compass watch
/home/bit2qubit/Documents/bit2qubit.github.io/Rakefile:81:in `spawn'
/home/bit2qubit/Documents/bit2qubit.github.io/Rakefile:81:in`block in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/task.rb:228:in `call'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/task.rb:228:in`block in execute'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/task.rb:223:in `each'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/task.rb:223:in`execute'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/task.rb:166:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/task.rb:159:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/task.rb:152:in`invoke'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/application.rb:143:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/application.rb:101:in`block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/application.rb:101:in `each'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/application.rb:101:in`block in top_level'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/application.rb:110:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/application.rb:95:in`top_level'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/application.rb:73:in `block in run'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/application.rb:160:in`standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/application.rb:70:in `run'
/var/lib/gems/1.9.1/gems/rake-0.9.6/bin/rake:37:in`<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in`<main>'
Tasks: TOP => preview
bit2qubit@bit2qubit-1001P:~/Documents/bit2qubit.github.io$ Configuration from /home/bit2qubit/Documents/bit2qubit.github.io/_config.yml
Auto-regenerating enabled: source -> public
[2013-11-22 11:29:26] regeneration: 92 files changed

uname -a
Linux bit2qubit-1001P 3.11.0-12-generic #19-Ubuntu SMP Wed Oct 9 16:12:00 UTC 2013 i686 i686 i686 GNU/Linux

ruby 1.9.3p194 (2012-04-20 revision 35410) [i686-linux]

rake, version 0.9.6

**Comment by chintan100** [comment]
Thanks, @bit2qubit. The above code solved the issue for me as well.
