### ISSUE TITLE
BUG: start, mark, and linenos don't work in code blocks

### ISSUE THREAD

**Issue by arielelkin** [imathis/octopress#1472]
This is a problem with codeblock and backtick code blocks. 

Here's how the samples from the documentation are rendering on a clean install of octopress: 

![IMG](http://i.imgur.com/P1c9vVl.png)

Result obtained by doing this: 

```
` ` `coffeescript Coffeescript Tricks start:51 mark:52,54-55
# Given an alphabet:
alphabet = 'abcdefghijklmnopqrstuvwxyz'

# Iterate over part of the alphabet:
console.log letter for letter in alphabet[4..8]
` ` `
```

and this:

```
{% codeblock Coffeescript Tricks lang:coffeescript start:51 mark:52,54-55 %}
# Given an alphabet:
alphabet = 'abcdefghijklmnopqrstuvwxyz'

# Iterate over part of the alphabet:
console.log letter for letter in alphabet[4..8]
{% endcodeblock %}
```

**Comment by treyhunner** [comment]
I also stumbled upon [this page](http://octopress.org/docs/plugins/backtick-codeblock/) and experienced the same issue.

**Comment by minamotoasahi** [comment]
I meet the same issue,, is there a complete solution? would you like to help me a description? (my English is very poor...)

**Comment by parkr** [comment]
Hello, Octopress 2 is not supported. Sorry for the trouble here! If someone has a very small, targeted PR that fixes this, feel free to CC me in it.
