### ISSUE TITLE
Help installing ffi gem

### ISSUE THREAD

**Issue by kaushalmodi** [imathis/octopress#1611]
Hi,

I have the ffi library installed in a folder in my home directory as I don't have root access to the machine on which I am trying to install octopress. I was able to sucessfully install older version of octopress. But the latest version needs few more gems to be installed and `ffi` is the only gem I am having trouble installing.

I get the following `mkmf.log` when doing `gem install ffi`:

```
"gcc -o conftest -I/home/kmodi/usr_local/include/ruby-2.1.0/x86_64-linux -I/home/kmodi/usr_local/include/ruby-2.1.0/ruby/backward -I/home/kmodi/usr_local/include/ruby-2.1.0 -I.     -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration conftest.c  -L. -L/home/kmodi/usr_local/lib -Wl,-R/home/kmodi/usr_local/lib -L/home/kmodi/usr_local/lib -lffi     -Wl,-R -Wl,/home/kmodi/usr_local/lib -L/home/kmodi/usr_local/lib -lruby-static  -lpthread -lrt -lgmp -ldl -lcrypt -lm   -lc"
/usr/bin/ld: cannot find -lffi
collect2: ld returned 1 exit status
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

The error says that lffi is not found. But `ffi.h` actually exists in `~/usr_local/lib/libffi-3.0.13/include/ffi.h` and I also have `~/usr_local/lib/pkgconfig/libffi.pc`.

How do I make `gem install` look for ffi in that location?

I understand that this issue is not octopress related but I'd appreciate if someone could help me out.

Thanks!

**Comment by meefik** [comment]
For Debian/Ubuntu try:
```
apt-get install build-essential ruby-dev
```

**Comment by kaushalmodi** [comment]
@meefik Thanks for the response. The tricky situation is that I don't have sudo access on my machine (work machine). So I have to install all the dependencies manually in my `$HOME`. So the above wouldn't work. 

Also I had posted this question many years ago :). The installation dependency hell made me switch to [Hugo](https://gohugo.io) ever since. 

I'll close this comment as I see that there is no way out other than what you suggested. And that's a fine solution if you have sudo access on the machine.
