### ISSUE TITLE
jekyll 2.3.0 | Error:  undefined method 'gsub' for #<Array:XXXXXXXXXXX>

### ISSUE THREAD

**Issue by petersellars** [imathis/octopress#1635]
I am getting the above error when generating using rake generate

Full Error:

```
Liquid Exception: undefined method 'gsub' for #<Array:XXXXXXXX> in atom.xml
jekyll 2.3.0 | Error:  undefined method 'gsub' for #<Array:XXXXXXXXXXX>
```

I have cloned the repository changed the URL added a new post, so not sure what this Exception refers to - is there a way for me to get more information into these errors?

**Comment by abepetrillo** [comment]
also reproduced this in jekyll `2.5.3`
