### ISSUE TITLE
a little question about "rake generation"

### ISSUE THREAD

**Issue by zxhfirefox** [imathis/octopress#1651]
when I use rake generation, I got this error:
jekyll 2.4.0 | Error:  Pygments can't parse unknown language: </p>.
I can not find where I am wrong in my markdown file.

but if I use jekyll build，there will be not error.

**Comment by dgmstuart** [comment]
Is this some kind of regression? I've just updated Octopress for the first time in a long time and I'm getting this issue:

    jekyll 2.3.0 | Error:  Pygments can't parse unknown language: ruby</p>.

...with an old post containing the following backtick code block:

    You can even pass multiple suffixes as arguments:
    ```ruby
    > "foo.qux".end_with?("bar", "baz", "qux")
    #=> true
    ```

(I used the print `str`/`lang` trick suggested above to identify the problematic line)
 
Inserting a blank line before the backtick line mysteriously stops this error from happening, but other code blocks don't have that blank line and don't cause the error. _Note: there's no space after the backticks and adding one didn't fix the issue._

Bizarrely, the preceding paragraph didn't lead to this issue:

    But of course in ruby there's a much more expressive way:
    ```ruby
    > "foo.bar".end_with?(".bar")
    #=> true
    > "foo.bar.baz".end_with?(".bar")
    #=> false
    ```

On the flipside I'm _not_ having issues with code blocks inside numbered lists - e.g the following works fine: 

    1. Update apt-get:
     
            apt-get update

**Comment by dgmstuart** [comment]
I've done some more investigation and the following post causes the error:
    
    ---
    layout: post
    title: "Matching on a final segment of a string"
    date: 2014-06-04 19:55:14 +0100
    comments: true
    categories: [Ruby]
    ---
    x
    ```ruby
    >"
    ```

    ```ruby 
    ```

If I remove either the double quote after the `>`, or removing the first line (the `x`) then it generates without errors.

@parkr (or anyone else) should I submit this as a test case?(how?) Or create a new issue? To Octopress, or to pygments?

**Comment by baweaver** [comment]
A note, if you make this very trivial mistake it'll start screaming:

```
my text
```
code
```
```

Make sure to linebreak between paragraphs and codeblocks

**Comment by dgmstuart** [comment]
@baweaver thanks for the input, but I'm sad you felt you had to be so nasty about it :(

Octopress/Jekyll's markdown parsing (using [redcarpet](https://github.com/vmg/redcarpet)?) doesn't fail in general to understand fenced code blocks without a preceding linebreak - just in certain cases.

Redcarpet doesn't seem to document how it expects fenced code blocks to work, but for comparison, Github flavoured markdown [explicitly doesn't require a linebreak](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks): 

> Note that although fenced code blocks don't have to be preceded by a blank line—unlike indented code blocks—we recommend placing a blank line before them to make the raw Markdown easier to read.

This is not a "trivial mistake".

**Comment by baweaver** [comment]
@dgmstuart - That wasn't meant as being nasty mate, not sure how you took it as that, but apologies either way. That was just meant to say it starts screaming about errors.

**Comment by dgmstuart** [comment]
@baweaver lol - so sorry: I totally read that as 

> if you make this very trivial mistake *I'll* start screaming:

#embarassednow

**Comment by baweaver** [comment]
/me shrugs

It happens, Monday us rough on all of us mate.
