### ISSUE TITLE
jekyll 2.4.0 | Error undefined method 'gsub' for nil:NilClass in blog/categories/test/atom.xml

### ISSUE THREAD

**Issue by ajzeigert** [imathis/octopress#1669]
I'm having a problem that sounds very similar to this issue:

https://github.com/imathis/octopress/issues/1635

I have installed the latest version (as of 10/20) of the bundle. Current jekyll version is 2.4.0.

Full text of error: 

```
$ rake generate
## Generating Site with Jekyll
identical source/stylesheets/screen.css
Configuration file: /Users/azeigert/octopress/_config.yml
            Source: source
       Destination: public
      Generating...
  Liquid Exception: undefined method `gsub' for nil:NilClass in blog/categories/test/atom.xml
jekyll 2.4.0 | Error:  undefined method `gsub' for nil:NilClass
```

Any help would be appreciated.

**Comment by justinelam** [comment]
I'm getting the same error. Here's the full stacktrace

```
 Liquid Exception: undefined method `gsub' for nil:NilClass in _layouts/standard-content-share.html
/Users/justinelam/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/rfc2396_parser.rb:304:in `escape': undefined method `gsub' for nil:NilClass (NoMethodError)
	from /Users/justinelam/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/common.rb:99:in `escape'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/filters.rb:148:in `uri_escape'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/liquid-2.6.2/lib/liquid/strainer.rb:43:in `invoke'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/liquid-2.6.2/lib/liquid/context.rb:82:in `invoke'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/liquid-2.6.2/lib/liquid/variable.rb:50:in `block in render'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/liquid-2.6.2/lib/liquid/variable.rb:38:in `each'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/liquid-2.6.2/lib/liquid/variable.rb:38:in `inject'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/liquid-2.6.2/lib/liquid/variable.rb:38:in `render'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/liquid-2.6.2/lib/liquid/block.rb:109:in `block in render_all'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `each'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `render_all'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/liquid-2.6.2/lib/liquid/block.rb:82:in `render'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/liquid-2.6.2/lib/liquid/template.rb:128:in `render'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/liquid-2.6.2/lib/liquid/template.rb:138:in `render!'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:106:in `render_liquid'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:205:in `render_all_layouts'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:239:in `do_layout'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/page.rb:122:in `render'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:298:in `block in render'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `each'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `render'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:51:in `process'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/bin/jekyll:23:in `load'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/bin/jekyll:23:in `<main>'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/justinelam/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by parkr** [comment]
Somehow, `nil` is being passed to `uri_escape`.

**Comment by cykhoo** [comment]
I had a similar error, which turned out to be caused by using the digits 404 in the title tag in the YAML front matter of our 'not found' error page.

Quoting the digits

`title: '404'`

solved the problem.

**Comment by Edwik** [comment]
:( There are some tutorial in 2016 jekill installation for windows ?

**Comment by koppor** [comment]
Google often points to this page, so here a solution for the googlers:

Turn `{{ page.author | markdownify}}` into following

```
  {% capture author %}{{ page.author }}{% endcapture %}
  {{author | markdownify}}
```

@Edwik Check out https://github.com/JabRef/blog.jabref.org/#installation

**Comment by SharvariNagesh** [comment]
Even I am facing a similar problem while running cap deploy. Can you please help me with this. Here is the trace output : 

cap omqa deploy --trace
** Invoke omqa (first_time)
** Execute omqa
** Invoke load:defaults (first_time)
** Execute load:defaults
cap aborted!
NoMethodError: undefined method `gsub' for nil:NilClass
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.8.0/lib/capistrano/defaults.rb:2:in `block in <top (required)>'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.8.0/lib/capistrano/configuration/validated_variables.rb:89:in `block in assert_valid_now'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.8.0/lib/capistrano/configuration/validated_variables.rb:88:in `each'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.8.0/lib/capistrano/configuration/validated_variables.rb:88:in `assert_valid_now'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.8.0/lib/capistrano/configuration/validated_variables.rb:44:in `set'
config/deploy.rb:3:in `<top (required)>'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.8.0/lib/capistrano/setup.rb:27:in `load'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.8.0/lib/capistrano/setup.rb:27:in `block (3 levels) in <top (required)>'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.8.0/lib/capistrano/configuration/variables.rb:32:in `untrusted!'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.8.0/lib/capistrano/setup.rb:26:in `block (2 levels) in <top (required)>'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.8.0/lib/capistrano/application.rb:14:in `run'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano-3.8.0/bin/cap:3:in `<top (required)>'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/bin/cap:23:in `load'
/Users/sharvarinagesh/.rbenv/versions/2.3.1/bin/cap:23:in `<main>'
Tasks: TOP => omqa
Outwares-MacBook-Pro-

**Comment by parkr** [comment]
@SharvariNagesh This is the issue tracker for Octopress – can you please raise that with the Capistrano maintainers?
