### ISSUE TITLE
`rake preview` not displaying `published: false` posts 

### ISSUE THREAD

**Issue by TheChymera** [imathis/octopress#1675]
I have had this problem for a few months now, but I kept putting it off believing it had something to do with my theme. Today I finally checked with the default octopress theme, and I could in fact reproduce it. As per [the docs](http://octopress.org/docs/blogging/), posts marked as `published: false` should still show up when visualizing the blog via `rake preview`. Over here, they do not.

My post:
 
```
---
layout: post
title: "How to read science news"
date: 2014-11-01 01:17:20 +0200
comments: true
categories: [science, epistemology, education]
published: false
---

TExt text text
```

I still get noticed in-terminal after updates to this post:

```
Regenerating: 1 files at 2014-11-02 02:38:24 ...done.
```

but it is not displayed.

**Comment by plttn** [comment]
~~Throwing my thoughts in here, I'd much prefer the jekyll format of drafts going into a separate folder, which is what i've got going on with some custom rake tasks, but I can't easily preview them without publishing them to a non production branch.~~

And after typing the above, I realized simply changing my rake preview task to pass "--drafts" did the trick.

**Comment by Blaisorblade** [comment]
> I'd much prefer the jekyll format of drafts going into a separate folder

Same here — `published: false` posts have a publishing date already assigned, which seems wrong, while drafts are fine. Luckily enough, octopress 3 reverts to using drafts by default (AFAICS from its README).

**Comment by imathis** [comment]
This isn't going to be added to Octopress. Jekyll is deprecating the `published: false` system in favor of their new `_drafts/` feature.

**Comment by LCamel** [comment]
The "Blogging Basics" page is still suggesting "published: false".

http://octopress.org/docs/blogging/
