### ISSUE TITLE
Rake generate fails possibly from Liquid exception

### ISSUE THREAD

**Issue by acgetchell** [imathis/octopress#1705]
I've just re-init'd my blog on Octopress following the directions here:

http://blog.zerosharp.com/clone-your-octopress-to-blog-from-two-places/

The first error I ran into was:

┌─[adam][Hapkido][±][source ✗][~/octopress]
└─▪ rake generate
rake aborted!
Gem::LoadError: You have already activated rake 10.4.2, but your Gemfile requires rake 0.9.2.2. Prepending `bundle exec` to your command may solve this.

I fixed this by going into Gemfile.lock and changing rake to (10.4.2)

Now it seems as though Liquid doesn't like 301 redirects from my old blog:

┌─[adam][Hapkido][±][source ✗][~/octopress]
└─▪ rake generate
## Generating Site with Jekyll

identical source/stylesheets/screen.css 
Configuration from /Users/adam/octopress/_config.yml
Building site: source -> public
Liquid Exception: Gist replied with 301 for https://gist.github.com/raw/926994/ in 2011-04-19-embedding-gists-in-blogger.html
/Users/adam/octopress/plugins/gist_tag.rb:86:in `get_gist_from_web'
/Users/adam/octopress/plugins/gist_tag.rb:33:in`render'
/Library/Ruby/Gems/2.0.0/gems/liquid-2.3.0/lib/liquid/block.rb:94:in `block in render_all'
/Library/Ruby/Gems/2.0.0/gems/liquid-2.3.0/lib/liquid/block.rb:92:in`collect'
/Library/Ruby/Gems/2.0.0/gems/liquid-2.3.0/lib/liquid/block.rb:92:in `render_all'
/Library/Ruby/Gems/2.0.0/gems/liquid-2.3.0/lib/liquid/block.rb:82:in`render'
/Library/Ruby/Gems/2.0.0/gems/liquid-2.3.0/lib/liquid/template.rb:124:in `render'
/Library/Ruby/Gems/2.0.0/gems/liquid-2.3.0/lib/liquid/template.rb:132:in`render!'
/Library/Ruby/Gems/2.0.0/gems/jekyll-0.12.0/lib/jekyll/convertible.rb:79:in `do_layout'
/Users/adam/octopress/plugins/post_filters.rb:167:in`do_layout'
/Library/Ruby/Gems/2.0.0/gems/jekyll-0.12.0/lib/jekyll/post.rb:195:in `render'
/Library/Ruby/Gems/2.0.0/gems/jekyll-0.12.0/lib/jekyll/site.rb:200:in`block in render'
/Library/Ruby/Gems/2.0.0/gems/jekyll-0.12.0/lib/jekyll/site.rb:199:in `each'
/Library/Ruby/Gems/2.0.0/gems/jekyll-0.12.0/lib/jekyll/site.rb:199:in`render'
/Library/Ruby/Gems/2.0.0/gems/jekyll-0.12.0/lib/jekyll/site.rb:41:in `process'
/Library/Ruby/Gems/2.0.0/gems/jekyll-0.12.0/bin/jekyll:264:in`<top (required)>'
/usr/bin/jekyll:23:in `load'
/usr/bin/jekyll:23:in`<main>'
Build Failed

The corresponding blog entry is:

http://www.adamgetchell.org/blog/2011/04/19/embedding-gists-in-blogger/

**Comment by iphyer** [comment]
However,I tried this and succeeded.

```
## Generating Site with Jekyll
overwrite source/stylesheets/screen.css 
/var/lib/gems/1.9.1/gems/maruku-0.6.0/lib/maruku/input/parse_doc.rb:22:in `<top (required)>': iconv will be deprecated in the future, use String#encode instead.
Configuration from /home/iphyer/Develop/Blog/octopress/_config.yml
Building site: source -> public
Successfully generated site: source -> public
```
