### ISSUE TITLE
rake deploy prompts for username/password

### ISSUE THREAD

**Issue by vcardillo** [imathis/octopress#1706]
When I run `rake deploy`, I'm being prompted for my GitHub username/password. Is there a reason for this? Any way to tell it to use SSH authentication?

**Comment by parkr** [comment]
`cd _deploy && git remote -v`

If that outputs an `https://` remote then change it to SSH.

**Comment by jfonte** [comment]
Just going to put this here to save people a few clicks https://help.github.com/articles/changing-a-remote-s-url/
