### ISSUE TITLE
Post url changes after rebuilding in different timezone

### ISSUE THREAD

**Issue by Shridhad** [imathis/octopress#1716]
From India I deployed my blog with following post date

 ```
 date: 2015-01-06 07:15:57 +0530
```

the post got published with url `/blog/2015/01/06/title` after some days, when I was in USA I made some changes and redeployed, then the url of post got changed to `/blog/2015/01/05/title`.

Everything(links form homepage, archives) was working fine, except Facebook like counts, +1, twitter tweet count and reference from external sites.

**Comment by imathis** [comment]
I believe settingt the `timezone` for your blog in the _config.yml should help keep things on the same timezone.

**Comment by Shridhad** [comment]
Thanks, setting `timezone` to `Asia/Kolkata` in the `_config.yml` solved the issue. Thanks.
Closing the issue.
