### ISSUE TITLE
I lost my octopuses local folder and can't find `source` branch in my github page , How do i continue blogging ?

### ISSUE THREAD

**Issue by yask123** [imathis/octopress#1719]
Unfortunately i deleted the octopress folder .
I had deployed my website here : https://github.com/yask123/yask123.github.io.git

This repo doesn't contain `source` branch , how do i continue blogging ?

**Comment by imathis** [comment]
Ugh, I'm really sorry. If you don't have a local backup and you haven't keep a backup on GitHub, there is not much you can do besides copy your content and reverse engineer your site. I feel really bad for you. I hope you're able to recover something.

**Comment by yask123** [comment]
ah! Please write in Red in the octopress documentation instructions to make the backup of the source.
