### ISSUE TITLE
SSD went bad, possible to get blog by cloning my blog repo?

### ISSUE THREAD

**Issue by jhwhite** [imathis/octopress#1735]
My SSD went bad and I lost all my data. Can I just pull down my repo from github? It's actually been a while since I published a post using Octopress and I can't find the sources/_posts folder when I cloned.

**Comment by imathis** [comment]
Oof. I'm sorry you lost a drive. If you pushed your source to GitHub you should be fine. If you only ever pushed your compiled site, your only option is to manually recreate the source/_posts contents.

**Comment by jhwhite** [comment]
When you say manually create, do you mean go through the steps in setting up the initial Octopress installation?

**Comment by imathis** [comment]
If you clone from your repository have you tried checking out the source branch? If you've been pushing your site source, that's probably where it is. The master branch will contain your published code. When I say "manually create" I mean, copy content and recreate your site as if your setting up Octopress for the first time. It stinks, but if you've lost your source and never pushed it, that's the only option left.

**Comment by jhwhite** [comment]
I totally forgot that there was a source branch. I'll play around with this more tonight. I haven't published a post in 11 months.

**Comment by imathis** [comment]
Good luck! (I'm going to close this issue, since it's a discussion, not a defect. Feel free to post back though).

**Comment by jhwhite** [comment]
So I pulled my repo, created a new blog post, but when I do `rake deploy` I get:

```
## Pushing generated _deploy website
To git@github.com:jhwhite/jhwhite.github.io.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:jhwhite/jhwhite.github.io.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

What am I missing to be able to deploy again?

**Comment by jhwhite** [comment]
OK So I got it pushed, but I lost one blog post, and the new post isn't formatted correctly when you view it.

Main page is fine: https://jhwhite.github.io/

Article view for new article is not: https://jhwhite.github.io/blog/2015/07/03/checking-inventory-at-your-local-barnes-and-noble/
