### ISSUE TITLE
java code snippet failed

### ISSUE THREAD

**Issue by romanman** [imathis/octopress#1740]
Got that one, is there any option for java snippets ?

```
jekyll 2.5.3 | Error:  Pygments can't parse unknown language: [Java].
```

**Comment by imathis** [comment]
That doesn't seem right. I have never had a problem doing syntax highlighting on Java. Have you tried using lowercase `java` instead of `Java`?

**Comment by romanman** [comment]
@imathis : thanks figured it out.
