### ISSUE TITLE
When I upgraded the Mac system, I can't Preview

### ISSUE THREAD

**Issue by liuchungui** [imathis/octopress#1749]
Work well in Mac10.10, but when I upgraded to Mac10.11, I input command 'rake preview', got following error.

$rake preview
Starting to watch source with Jekyll and Compass. Starting Rack on port 4000
rake aborted!
Errno::ENOENT: No such file or directory - compass
/Users/user/git/octopress/Rakefile:85:in `spawn`
/Users/user/git/octopress/Rakefile:85:in `block in <top (required)>`
Tasks: TOP => preview
(See full trace by running task with --trace)
userdeMacBook-Pro:octopress user$ Configuration file: /Users/user/git/octopress/_config.yml
            Source: source
       Destination: public
      Generating... 
                    done.
 Auto-regeneration: enabled for 'source'

**Comment by schalkneethling** [comment]
I am getting exactly the same error on El Capitan. `rake generate` works fine (seemingly) but `rake watch` fails with the same error.

**Comment by schalkneethling** [comment]
Here is my trace:

```
$ rake preview --trace
** Invoke preview (first_time)
** Execute preview
Starting to watch source with Jekyll and Compass. Starting Rack on port 4000
rake aborted!
Errno::ENOENT: No such file or directory - jekyll
/Users/espressive/repos/schalk-neethling/Rakefile:84:in `spawn'
/Users/espressive/repos/schalk-neethling/Rakefile:84:in `block in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Library/Ruby/Gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/bin/rake:37:in `<main>'
Tasks: TOP => preview
```

**Comment by schalkneethling** [comment]
Alrighty @liuchungui so here is the tl;dr of what I did to get this to work on El Capitan:

Install rbenv [https://github.com/sstephenson/rbenv]
Install ruby 2.2.2 `rbenv install 2.2.2`
Now, inside the root of your octopress blog do

```
rbenv local 2.2.2
gem install bundler
rbenv rehash
bundle install
```

`rake preview` etc. should now all work. I assume it has something to do with the Ruby version that comes with El Capitan although not 100% certain. HTH!

**Comment by liuchungui** [comment]
Thank you, it work for me.

**Comment by liuchungui** [comment]
I edit Gemfile, and change source.

```
source 'https://ruby.taobao.org/'

group :development do
  gem 'rake', '~> 10.0'
  gem 'jekyll', '~> 2.0'
  gem 'octopress-hooks', '~> 2.2'
  gem 'octopress-date-format', '~> 2.0'
  gem 'jekyll-sitemap'
  gem 'rdiscount', '~> 2.0'
  gem 'RedCloth', '~> 4.2.9'
  gem 'haml', '~> 4.0'
  gem 'compass', '~> 1.0.1'
  gem 'sass-globbing', '~> 1.0.0'
  gem 'rb-fsevent', '~> 0.9'
  gem 'stringex', '~> 1.4.0'
end

gem 'sinatra', '~> 1.4.2'
```

**Comment by JonyFang** [comment]
This is what I did to get this to work on El Capitan:

1.Clear git cache
{% codeblock lang:ruby %}
rm -rf /usr/local/.git
{% endcodeblock %}

2.Uninstall Homebrew：
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"

3.Install RVM
{% codeblock lang:ruby %}
curl -L https://get.rvm.io | bash -s stable --ruby
{% endcodeblock %}

4.Install Ruby 2.2.3:
{% codeblock lang:ruby %}
rvm install ruby-2.2.3
{% endcodeblock %}

{% codeblock lang:ruby %}
ram use 2.2.3
{% endcodeblock %}

{% codeblock lang:ruby %}
rvm rubygems latest
{% endcodeblock %}

Run `ruby --version` to be sure you're using Ruby 2.2.3.

4.Next, install dependencies.

{% codeblock lang:ruby %}
cd octopress
sudo gem install bundler
bundle install
{% endcodeblock %}


`rake preview` etc. now all work. It's work for me in EI Capitan.

**Comment by aertoria** [comment]
Great post. Every time osx upgrade there always will be something

**Comment by caiyue1993** [comment]
Thank you @JonyFang . I've tried lots of methods to fix it,finally it works on my EI Capitan. However,ruby 2.2.2 is also OK.

**Comment by dfalster** [comment]
Thanks for this @schalkneethling, solved my issue
