### ISSUE TITLE
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1] when excecute "rake deploy"

### ISSUE THREAD

**Issue by nauliajati** [imathis/octopress#1762]
hi all, i got this error messages when i am trying to execute "rake deploy" on my terminal,
## Deploying website via Rsync

ssh: connect to host domain.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1]
FAILED

anyone can help me please? i am frustrated to this error.

**Comment by dikiaap** [comment]
https://github.com/octopress/octopress

**Comment by nauliajati** [comment]
nice dude, just change deploy_default "resync" to "push" on Rakefile
https://gist.github.com/SunDi3yansyah/26e60e44ba5e23875a57/revisions

**Comment by dikiaap** [comment]
Ok, close if ur fix the issues. :+1:

**Comment by SunDi3yansyah** [comment]
cheers :dancer:
