### ISSUE TITLE
utf-8 not working in code blocks

### ISSUE THREAD

**Issue by benben** [imathis/octopress#232]
given the following post:

``````

---

test post with äüß

``` ruby

def ruby
# ä
end

```
``````

creates a post looking like this:

```
test post with äüß

1 def ruby
2 # 채
3 end
```

So, I think there is something wrong with encoding. The strange thing is: five ä ("äääää") does work, but less then five doesn't work.

/edit/
if the codeblock contains more than 4 special chars, then encoding works. no matter where there are placed.

**Comment by woterwang** [comment]
thanks scss file  header write @charset "utf-8"
Solved the problem
