### ISSUE TITLE
Liquid Exception: Variable '{{ {0}' was not properly terminated with regexp: /\}\}/  in

### ISSUE THREAD

**Issue by huobazi** [imathis/octopress#466]
Liquid Exception: Variable '{{document.forms[0].__SCROLLPOS_TOP.value = {0}' was not properly terminated with regexp: /}}/  in 2004-09-20-scrollpage.markdown
Liquid Exception: Variable '{{ {0}' was not properly terminated with regexp: /}}/  in 2007-08-05-advertisementlazyloadingcontrol.markdown
Liquid Exception: Variable '{{ {0}' was not properly terminated with regexp: /}}/  in atom.xml
Liquid Exception: Variable '{{ {0}' was not properly terminated with regexp: /}}/  in atom.xml

the mk file:

[https://gist.github.com/1970621](https://gist.github.com/1970621)

**Comment by 1step2hell** [comment]
@samselikoff Thank you, but I found another problem:
{% raw %} {{some-text}} {% endraw %}
If some-text also contains {% raw %}   {% endraw %}, liquid throws exception: Unknown tag 'endraw'.

You may wonder why there are people do this weird stuff, Yeah I did, I actually want to record this issue in markdown file. So I need show the whole string "{% raw %} {% include file.ext %} {% endraw %}"  as raw text. And I couldn't make it.
Thanks again.

**Comment by sajidnisar** [comment]
It worked for me with `} }` (use space in between the curlies).
