### ISSUE TITLE
Liquid Exception: Unknown tag 'include_array' in index.html 

### ISSUE THREAD

**Issue by aatishnn** [imathis/octopress#585]
Using default installation, I am getting this while doing `rake generate`:

```
[user@sun octopress]$ rake generate
## Generating Site with Jekyll
unchanged sass/screen.scss
WARNING: Could not read configuration. Using defaults (and options).
    syntax error on line 92, col 0: `disqus_show_comment_count: false'
Building site: /home/user/octopress -> /home/user/octopress/_site
Liquid Exception: Unknown tag 'include_array' in index.html
Successfully generated site: /home/user/octopress -> /home/user/octopress/_site
```

I also don't know why I am getting error on `disqus_show_comment_count:false`.

**Comment by philsturgeon** [comment]
Sorry to necro-bump this issue, but I'm getting this problem and all roads lead here.

I have upgraded from some super old version to latest. The site mostly seems to load ok but with an error, which is stopped deployments.

I've not got a `rake update` but I did `bundle exec rake update_source` and `bundle exec rake update_style`, which have not solved the problem. Running the `generate` task is also producing the error, so @Amit-Thawait's solution doesn't work for me.

```
$ bundle exec rake generate
## Generating Site with Jekyll
    write source/stylesheets/screen.css
Configuration file: /Users/phil/src/phptownhall.com/_config.yml
            Source: source
       Destination: public
      Generating... 
  Liquid Exception: Unknown tag 'include_array' in _layouts/post.html
jekyll 2.5.3 | Error:  Unknown tag 'include_array'
```

Any ideas?
