### ISSUE TITLE
Can't override styles using _styles.scss

### ISSUE THREAD

**Issue by thiagoperes** [imathis/octopress#707]
Hello,

I'm using the bootstrap theme and I'm trying to change the default theme with my own styles. Problem is whenever I add a style to _styles.scss, it gets detected but nothing seems to change.

I also tried changing _layout.scss, uncommenting the lines provided as example, but they don't work aswell.

All I want to do is replace the default bootstrap.css with my custom one, like change colors and make the grid narrower.

Thank you.

**Comment by fmquaglia** [comment]
I had exactly the same problem as @blaenk .
Thanks for sharing your answer, man.

Make sure you run ```rake clean```
