### ISSUE TITLE
GitHub gist changes break gist plugin formatting

### ISSUE THREAD

**Issue by lukekarrys** [imathis/octopress#847]
Not sure exactly what the issue is but [GitHub updated their gists today](https://github.com/blog/1276-welcome-to-a-new-gist) and it looks like it breaks a few things with regards to the gist plugin.

Here is how a gist on my site looks: http://lukecod.es/blog/2012/02/14/pitchfork-dot-com-album-rating-api/

It looks like at least two things are broken:
- That page ([source](https://github.com/lukekarrys/lukecod.es/blob/master/source/_posts/2012-02-14-pitchfork-dot-com-album-rating-api.markdown#code)) is only supposed to bring in one gist file and now it brings in all files
- Formatting and styling

I plan to take a look at this over the next couple days, but thought I'd open an issue to avoid duplicates and in case anyone wants to take a look at it sooner.

**Comment by info-maps** [comment]
This fix my issue with formatting.
.gist div.line{
    text-align: left;
}

**Comment by pablocobelli** [comment]
I realize this is an old thread, but your discussion is the closest one to my question that I could find.

Would you, by any chance, know what is github doing to generate the html code for the embed? I mean, which syntax highlighter and style are used to generate the arguments in the documentwrite commands? Thanks!

**Comment by parkr** [comment]
> what is github doing to generate the html code for the embed

@pablocobelli The relevant code is open source: [jekyll-gist](https://github.com/jekyll/jekyll-gist/blob/master/lib/jekyll-gist/gist_tag.rb).
